# encoding: utf-8
# This file is distributed under New Relic's license terms.
# See https://github.com/newrelic/newrelic-ruby-agent/blob/main/LICENSE for complete details.

module Newrelic
  module TelemetrySdk
    module Util
      extend self

      HEX_DIGITS = (0..15).map{|i| i.to_s(16)}

      module_function

      # This method intentionally does not use SecureRandom, because it relies
      # on urandom, which raises an exception in MRI when the interpreter runs
      # out of allocated file descriptors.
      # The guids generated by this method may not be _secure_, but they are
      # random enough for our purposes.
      def generate_guid length = 16
        guid = ''
        length.times do |a|
          guid << HEX_DIGITS[rand(16)]
        end
        guid
      end

      # Should be used for all timing. If we need to support Ruby 2.0 where we
      # can't use a monotonic clock, we can make this conditional based on version.
      def time_to_ms time = Process.clock_gettime(Process::CLOCK_MONOTONIC)
        (time.to_f * 1000).round
      end
    end
  end
end
